# Generated by Django 5.1.7 on 2025-03-19 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tran_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
