# Generated by Django 5.1.7 on 2025-03-21 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_tran_id'),
        ('restaurant', '0002_remove_menuitem_menu_menuitem_restaurant_delete_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='restaurant',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order_restaurant', to='restaurant.restaurant'),
            preserve_default=False,
        ),
    ]
